/** Regenerates PROGRESS.md from context ledgers (CLAUDE.md §8 — never hand-edit the rollup). */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const contexts = readdirSync(join(root, "libs")).filter((c) =>
  existsSync(join(root, "libs", c, "REQUIREMENTS.md"))
);

const rows: string[] = [];
const totalsAgg: Record<string, number> = {};
for (const ctx of contexts.sort()) {
  const md = readFileSync(join(root, "libs", ctx, "REQUIREMENTS.md"), "utf8");
  const totalsLine = md.match(/^Totals: (.+)$/m)?.[1] ?? "";
  for (const part of totalsLine.split("·")) {
    const m = part.trim().match(/^(\d+) ([A-Z_]+)$/);
    if (m) totalsAgg[m[2]!] = (totalsAgg[m[2]!] ?? 0) + Number(m[1]);
  }
  rows.push(`| ${ctx.toUpperCase()} | ${totalsLine} |`);
}

const order = ["DONE", "IN_REVIEW", "IN_PROGRESS", "READY", "PROPOSED", "DEFERRED", "BLOCKED"];
const grand = order.map((k) => `${totalsAgg[k] ?? 0} ${k}`).join(" · ");

writeFileSync(
  join(root, "PROGRESS.md"),
  `# Progress — generated rollup

> Generated by \`scripts/progress.ts\` from context ledgers. Do not hand-edit.
> Last refresh: ${new Date().toISOString().slice(0, 10)}

**All contexts:** ${grand}

| Context | Totals |
|---------|--------|
${rows.join("\n")}

Details: \`libs/<ctx>/REQUIREMENTS.md\` · history: \`libs/<ctx>/LOG.md\`.
`
);
console.log("PROGRESS.md refreshed:", grand);
